---
title: "LA Crime Data from 2010 to 2019"
output: html_document
---

```{r setup, include=FALSE}
#Setting up environment
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading}
pacman::p_load(knitr, dplyr)
df = read_csv("Crime_Data.csv")

#The column "Crime Code 4" is totally filled with NA's, so we can discard it. In addition to that, 
# we can get rid of the first column "DR Number"  which only indicates the crime id.
df$`Crime Code 4`= NULL
df$`DR Number`= NULL # ID del número de crimen

#Some more variables that are redundant
df$`Area ID`= NULL
df$`Weapon Used Code`= NULL
df$`Premise Code`= NULL
df$`Status Code`= NULL

#TOO DETAILED:do we need it?
df$`Reporting District` = NULL #It's 991 areas, we'll try to go on without it,
df$Location = NULL #GPS coordinates
#df$`Address`

#Regarding the time of the crime let's summarize it in 4 categories: morning, afternoon, evening and night.
df$`Time Occurred`=cut(as.integer(df$`Time Occurred`), c(0000,0601,1201,1801,max(df$`Time Occurred`)), labels=c("Night","Morning","Afternoon","Evening"))

#Regarding te age of the victim, let's summarize it in 4 categories: 
#         minor(<18), young adult(18-<30), adult(31-60), elder (>60)
df$`Victim Age`=cut(as.integer(df$`Victim Age`),c(0,17,30,59,max(df$`Victim Age`)))
    
# I create a new variable to calculate how many days took to report a crime 
df$Report = as.Date(df$`Date Reported`,"%m/%d/%Y")-as.Date(df$`Date Occurred`,"%m/%d/%Y")
# Maybe at the beginning and end of month crime ocurrences peak?

table(df$Report)

str(df)

```



